### ISSUE TITLE
thank you very much!!

### ISSUE THREAD

**Issue by Condiolov** [manahter/nCNC#1]
I managed to generate gcode easily !!
How do I translate to my language, I know I have to change the code, but how do I do it right here? The code worked in Blender 2.9 !! I tested only the basics! very functional! Congratulations!!

**Comment by nesivmi** [comment]
Glad you like it.
I was going to translate them all into English but I guess I forgot.
Will it be enough for you if I just flip places on the GUI.

**Comment by nesivmi** [comment]
> I managed to generate gcode easily !!
> How do I translate to my language, I know I have to change the code, but how do I do it right here? The code worked in Blender 2.9 !! I tested only the basics! very functional! Congratulations!!

Hello, I shared the new version here
[https://github.com/manahter/nCNC](https://github.com/manahter/nCNC)

**Comment by Condiolov** [comment]
Uaaaaal!!! Thank you very much!!
